spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ucat-boots-example-redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms

server:
  port: 7001


management:
  endpoints:
    web:
      exposure:
        include: "*"